# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbRating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
    ]
