# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160829_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(max_length=200),
        ),
    ]
