# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20160829_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.FloatField(default=0),
        ),
    ]
